# Generated by Django 4.2 on 2023-09-20 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="event",
            table="events",
        ),
    ]
