# Generated by Django 4.2 on 2023-09-29 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Event", "0003_eventlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventlog",
            old_name="participan",
            new_name="participant",
        ),
    ]
